### ISSUE TITLE
Add travis badge

### ISSUE THREAD

**Issue by SamVerschueren** [beatfreaker/text-meme#5]
Noticed `text-meme` and `text-meme-cli` are not added yet to travis although a `.travis.yml` file is present.

**Comment by beatfreaker** [comment]
@SamVerschueren after adding to travis it is failing while installing `canvas` because of [this](https://www.npmjs.com/package/canvas#installation) dependency .... any idea how to resolve it?

**Comment by SamVerschueren** [comment]
Here you go: https://docs.travis-ci.com/user/installing-dependencies/

**Comment by beatfreaker** [comment]
Thanks @SamVerschueren 
configured it but getting some issue in `Node.js:stable -> The command "eval npm install " failed`.
while it works fine with `0.10` and `0.12`

any suggestions?

**Comment by SamVerschueren** [comment]
For the interested people: https://travis-ci.org/beatfreaker/text-meme/jobs/98076679

Not quite sure why this is going wrong.

Have you tried installing `text-meme` on your own system in Node 5.2.0? Maybe something is wrong with `canvas` for that version.

**Comment by beatfreaker** [comment]
@SamVerschueren Yeah Node 5.2.0 was the issue `canvas` is not working in that environment and now added enabled `travis` in both module. Thanks for the help :)

**Comment by SamVerschueren** [comment]
You didn't add the badge to the README yet :).

I noticed you removed the `stable` entry in `.travis.yml`. If it's working on Node 4.x, maybe you should add Node 4 as an entry to travis and limit the [engines](https://github.com/beatfreaker/text-meme/blob/master/package.json#L13) property so that it cannot be installed on Node versions that aren't supported.
