### ISSUE TITLE
Add link to dependencies

### ISSUE THREAD

**Issue by SamVerschueren** [beatfreaker/text-meme#6]
`text-meme` uses `canvas` as dependency. But in order to use that, you need some stuff preinstalled as listed [here](https://www.npmjs.com/package/canvas#installation).

Maybe this should be documented (in `text-meme-cli` as well) as you will receive an error if you don't have that stuff installed.

**Comment by beatfreaker** [comment]
added [here](https://github.com/beatfreaker/text-meme#note) and [here](https://github.com/beatfreaker/text-meme-cli#note)
